definitions:
  apperror.AppError:
    properties:
      code:
        type: string
      developer_message:
        type: string
      message:
        type: string
    type: object
  user.CreateByPhoneDTO:
    properties:
      phone_number:
        example: "+79999999999"
        type: string
      verification_code:
        example: "123321"
        type: string
    type: object
  user.CreateByVkDTO:
    properties:
      phone_number:
        type: string
      vk_token:
        type: string
    type: object
  user.UpdateUserDTO:
    properties:
      city:
        type: string
      email:
        type: string
      id:
        type: string
      last_online:
        type: integer
      name:
        type: string
      phone_approved:
        type: boolean
      phone_number:
        type: string
      surname:
        type: string
      vk_id:
        type: string
    type: object
info:
  contact: {}
paths:
  /api/v1/users/del/id/{id}:
    delete:
      consumes:
      - application/json
      parameters:
      - description: User ID
        in: path
        name: user_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "204":
          description: ""
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/apperror.AppError'
      summary: Deletes user by id
      tags:
      - Users
  /api/v1/users/get/all:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: ""
        "400":
          description: ""
      summary: Returns data of all user_service
      tags:
      - Users
  /api/v1/users/get/id/{id}:
    get:
      consumes:
      - application/json
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: ""
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/apperror.AppError'
      summary: Returns user data by id
      tags:
      - Users
  /api/v1/users/get/id/{phone_number}:
    get:
      consumes:
      - application/json
      parameters:
      - description: Phone number
        in: path
        name: phone_number
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: ""
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/apperror.AppError'
      summary: Returns user data by phone number
      tags:
      - Users
  /api/v1/users/heartbeat:
    get:
      responses:
        "204":
          description: ""
        "400":
          description: ""
      summary: Heartbeat metric
      tags:
      - Metrics
  /api/v1/users/phone:
    post:
      consumes:
      - application/json
      parameters:
      - description: structure holds data for user creation by phone
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/user.CreateByPhoneDTO'
      produces:
      - application/json
      responses:
        "201":
          description: ""
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/apperror.AppError'
      summary: Create user by phone number and token
      tags:
      - Users
  /api/v1/users/send_verification/{phone_number}:
    get:
      consumes:
      - application/json
      parameters:
      - description: phone number where the code will be sent
        in: path
        name: phone_number
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: ""
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/apperror.AppError'
      summary: Sends verification code by phone number
      tags:
      - Users
  /api/v1/users/upd/:
    put:
      consumes:
      - application/json
      parameters:
      - description: update user struct
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/user.UpdateUserDTO'
      produces:
      - application/json
      responses:
        "204":
          description: ""
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/apperror.AppError'
      summary: Updates user data
      tags:
      - Users
  /api/v1/users/vk:
    post:
      consumes:
      - application/json
      parameters:
      - description: structure holds data for user creation by vk
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/user.CreateByVkDTO'
      produces:
      - application/json
      responses:
        "201":
          description: ""
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/apperror.AppError'
      summary: Create user by phone number and token
      tags:
      - Users
swagger: "2.0"
